/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";

const descriptions = [
  "As a resident and designer here in Palm Beach County, I understand what makes the local market tick. My focus is on helping small business owners move beyond generic templates and build a digital identity that works as hard as you do.",
  "I prioritize speed, security, and user experience because these are the foundations of building digital trust. Your website should be your most valuable employee, working 24/7 to turn visitors into long-term clients."
];

interface AboutTextSplitProps {
  title: string;
  descriptions: string[];
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const AboutInline = () => {
  return (
    <section aria-label="About section" className="py-20">
      <div className="flex flex-col gap-20 mx-auto w-content-width">
        <div className="flex flex-col md:flex-row gap-3 md:gap-15">
          <div className="w-full md:w-1/2">
            <TextAnimation
              text={"Local Design Partner for Your Growth"}
              variant={"slide-up"}
              gradientText={true}
              tag="h2"
              className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-balance"
            />
          </div>

          <div className="flex flex-col gap-2 w-full md:w-1/2">
            {descriptions.map((desc, index) => (
              <TextAnimation
                key={index}
                text={desc}
                variant={"slide-up"}
                gradientText={false}
                tag="p"
                className="text-xl md:text-2xl leading-snug text-balance"
              />
            ))}

            {(undefined || undefined) && (
              <div className="flex flex-wrap gap-3 mt-2 md:mt-3">
                {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
                {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
              </div>
            )}
          </div>
        </div>

        <div className="w-full border-b border-foreground/5" />
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
