// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Local Design Partner for Your Growth"
          descriptions={[
            "As a resident and designer here in Palm Beach County, I understand what makes the local market tick. My focus is on helping small business owners move beyond generic templates and build a digital identity that works as hard as you do.",
            "I prioritize speed, security, and user experience because these are the foundations of building digital trust. Your website should be your most valuable employee, working 24/7 to turn visitors into long-term clients.",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
