// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Grow?"
          text="Let’s build something incredible together. Schedule a free consultation for your local business today."
          primaryButton={{
            text: "Schedule Free Call",
            href: "#contact-form",
          }}
          secondaryButton={{
            text: "Send me an Email",
            href: "mailto:hello@pbcwebdesign.com",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
