// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Frequently Asked Questions"
          description="Need more clarity? Here are answers to the most common questions my clients have."
          items={[
            {
              question: "How long does a website project take?",
              answer: "Most projects take between 4-6 weeks from initial consultation to final launch.",
            },
            {
              question: "Do you offer SEO services?",
              answer: "Yes, every site I build is designed with SEO best practices and local search optimization in mind.",
            },
            {
              question: "What happens after the site launches?",
              answer: "I offer ongoing maintenance and support packages to ensure your site remains fast, secure, and updated.",
            },
            {
              question: "Can I edit the content myself?",
              answer: "Absolutely. I build on intuitive platforms that give you full control to update your text and images whenever you need.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/asian-woman-working-laptop-vacation-sitting-stairs_1303-15634.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
