// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroCenteredLogos from '@/components/sections/hero/HeroCenteredLogos';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroCenteredLogos
          avatarsSrc={[
            "http://img.b2bpic.net/free-photo/portrait-young-business-man-posing-with-crossed-arms_23-2149206526.jpg",
            "http://img.b2bpic.net/free-photo/blonde-woman-is-loooking-camera-by-crossing-arms-white-background_176474-115879.jpg",
            "http://img.b2bpic.net/free-photo/closeup-portrait-caucasian-happy-teacher-glasses_74855-9736.jpg",
            "http://img.b2bpic.net/free-photo/portrait-young-confident-businessman-wearing-glasses_158595-5360.jpg",
          ]}
          avatarText="Trusted by local small business owners"
          title="Design Websites That Grow Your Palm Beach Business"
          description="Stop struggling with templates. Get a custom, high-converting website designed to attract your local customers and drive meaningful results in South Florida."
          primaryButton={{
            text: "Get Your Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View My Portfolio",
            href: "#services",
          }}
          names={[
            "Coastal Decor",
            "Sun Valley Coffee",
            "Palm Beach Law",
            "Ocean Breeze Yoga",
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/desk-workplace-with-copy-space_1194-638352.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
