// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Results Matter"
          title="Data-Driven Success"
          description="I focus on the numbers that actually drive profit, not just pretty pixels."
          metrics={[
            {
              value: "150+",
              title: "Projects Completed",
              description: "Local business sites across Palm Beach.",
              imageSrc: "http://img.b2bpic.net/free-photo/cancer-oncology-hope-support-concept_53876-133885.jpg",
            },
            {
              value: "45%",
              title: "Avg Conversion Lift",
              description: "Helping brands turn more traffic into sales.",
              imageSrc: "http://img.b2bpic.net/free-photo/asian-woman-working-laptop-vacation-sitting-stairs_1303-15632.jpg",
            },
            {
              value: "98%",
              title: "Client Satisfaction",
              description: "Long-term relationships with every partner.",
              imageSrc: "http://img.b2bpic.net/free-photo/cute-desktop-with-office-appliances-keyboard_23-2147830062.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
