// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesDetailedCards from '@/components/sections/features/FeaturesDetailedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesDetailedCards
          tag="What I Do"
          title="Custom Web Design Solutions"
          description="I create websites optimized for speed, search engines, and maximum conversion rates."
          items={[
            {
              title: "SEO-Optimized Websites",
              description: "Rank higher in local searches in West Palm Beach and reach more of your customers every single day.",
              tags: [
                "SEO",
                "Performance",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/businessman-packed-suitcase-vacation-happily-working-guy-office-clothes-holds-laptop-looks-into-camera-blue-space-with-inflatable-circle_197531-15468.jpg",
            },
            {
              title: "Mobile-First Design",
              description: "Your customers use their phones more than anything else. I make sure your site looks perfect on every device.",
              tags: [
                "Responsive",
                "Mobile",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/female-artist-dressed-casually-working-her-sketch-while-drawing-something-sitting-her-workshop-creative-woman-being-involved-painting-people-hobby-creative-process-concept_273609-336.jpg",
            },
            {
              title: "Conversion Rate Strategy",
              description: "Turn more visitors into actual paying clients with strategic landing pages and clear calls to action.",
              tags: [
                "Strategy",
                "Growth",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-colorful-overloaded-bullet-journal_23-2150168680.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
